### ISSUE TITLE
Add CI building

### ISSUE THREAD

**Issue by Palid** [Opentopic/falcon-api#4]
The readme could use automatic building and status icons telling people if it actually works correctly. 

For open source projects there's a lot of available tools to automatically build and test the project. 
The most popular one for open source project is I think [Travis CI](https://travis-ci.org/).

For coverage and overall code quality there two similarly popular alternatives: [Code Climate](https://codeclimate.com/) and [Coveralls](https://coveralls.io/).

After setting the project up with CI you will receive a hyperlink for a badge, that you can easily add to your project that will show if current master's building correctly and it's coverage status/code quality. See for instance [Travis CI Embedding Status image](https://docs.travis-ci.com/user/status-images/).

**Comment by tomaszroszko** [comment]
Good idea with the badges, however, right now all builds are build and tests including code quality in our internal Jenkins instance, maybe at some point, we will think about moving that to Travis or similar tool to also get a badge. Right now probably there are more important things to do :)

Thx for suggestions

**Comment by tomaszroszko** [comment]
Unless Jan have some free time :) we can go with it 👍

**Comment by nineinchnick** [comment]
Added Travis.
